---
version: "2.0"

services:
  ghost:
    image: ghcr.io/zhajingwen/ghost-ipfs-bkup:latest
    expose:
      - port: 2368
        as: 80
        to:
          - global: true
        http_options:
          max_body_size: 524288000
        accept:
          - changeme.com
    env:
      - url=http://changeme.com
      - NODE_ENV=production
      - FILEBASE_BUCKET=shixiaolong
      - FILEBASE_ENDPOINT=https://s3.filebase.com
      - FILEBASE_ACCESS_KEY_ID=xx
      - FILEBASE_SECRET_ACCESS_KEY=xxx
      - BACKUP_ENCRYPTION_PASSWORD=x+x+I64=
      - FILEBASE_BACKUP_PATH=ghost
      - database__client=sqlite3
      - database__connection__filename=content/data/ghost.db  
      - mail__transport=SMTP
      - mail__options__host=smtp.resend.com
      - mail__options__port=587
      - mail__options__secure=false  
      - mail__options__requireTLS=true
      - mail__options__auth__user=resend
      - mail__options__auth__pass=re_bnx_9b6                
      - mail__from=noreply@resend.dev  

profiles:
  compute:
    ghost:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          size: 1.5Gi
  placement:
    akash:
      pricing:
        ghost:
          denom: uakt
          amount: 5000

deployment:
  ghost:
    akash:
      profile: ghost
      count: 1